apiVersion: v1
kind: Service
metadata:
  name: template-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: template-app
  type: ClusterIP
