apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

configMapGenerator:
  - name: template-app-config
    envs:
      - .env.config

# Adjust resources and replicas for production env
patches:
  - target:
      kind: Deployment
      name: template-app
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: template-app
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: app
                resources:
                  requests:
                    cpu: 200m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
