apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app: mimir
spec:
  type: ClusterIP
  selector:
    app: mimir
  ports:
    - name: http
      port: 9009
      targetPort: 9009
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-lens-proxy
  namespace: monitoring
  labels:
    app: prometheus
    component: server
    heritage: Helm
spec:
  type: ClusterIP
  selector:
    app: mimir
  ports:
    - name: http
      port: 9090
      targetPort: 9009
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app: mimir
spec:
  serviceName: mimir
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.14.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          args:
            - -target=all
            - -config.file=/etc/mimir/mimir.yaml
            - -auth.multitenancy-enabled=false
          ports:
            - containerPort: 9009
              name: http
          readinessProbe:
            httpGet:
              path: /ready
              port: 9009
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 9009
            initialDelaySeconds: 60
            periodSeconds: 20
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir
            - name: mimir-storage
              mountPath: /data
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-config
  volumeClaimTemplates:
    - metadata:
        name: mimir-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs-csi
        resources:
          requests:
            storage: 50Gi
